#!/usr/bin/env ruby

require "webrick"
require "churros_git_bot"

# manual-mode: run once, get data from argv
if ARGV.length == 3
  project_id = ARGV[0]
  mr_iid = ARGV[1]
  clone_url = ARGV[2]
  puts "Running in one-shot mode: 
  - Project ID       = #{project_id}
  - Merge request ID = #{mr_iid}
  - Clone URL        = #{clone_url}"

  should_fail = false
  ChurrosGitBot.update_houdini_progress_note project_id, clone_url, mr_iid
  should_fail = ChurrosGitBot.conflicting_migrations project_id, mr_iid
  ChurrosGitBot.wait_until_current_build_job_is_done project_id, mr_iid
  ChurrosGitBot.build_failed_because_of_volta project_id, mr_iid
  exit should_fail ? 1 : 0
end

puts "Running in server mode: listening for gitlab webhooks on port 3000..."

server = WEBrick::HTTPServer.new(:Port => 3000)

# listen to webhooks request on /mr
server.mount_proc "/mr" do |req, res|
  if req.request_method != "POST"
    res.status = 405
    res["Allow"] = "POST"
    res.body = "Method not allowed"
    next
  end

  # get merge request id
  input = JSON.parse(req.body)

  # get project id
  project_id = input["project"]["id"]
  mr_iid = input["object_attributes"]["iid"]
  clone_url = input["project"]["git_http_url"]

  ChurrosGitBot.update_houdini_progress_note project_id, clone_url, mr_iid

  res.status = 200
  res.content_type = "application/json"
  # res.body = JSON.generate(output)
end

trap("INT") { server.shutdown }

server.start
